### PR TITLE
upkeep/90: update support level from active to stable

### LINKED ISSUE #90: Update Support Level from Active to Stable
### Is your enhancement related to a problem? Please describe.

Once the following are completed:
- [x] #68
- [x] #69
- [ ] review old `wpsvg` "pro" repo for any other functionality to port into free plugin

... we can then work to update the support level for this plugin from Active to Stable as we can generally consider the optimal feature set of the plugin complete.  Tasks to complete this change:
- [ ] create a sticky forum post like https://wordpress.org/support/topic/read-this-before-you-post-64/
- [ ] make repo updates like https://github.com/10up/Ad-Refresh-Control/pull/73
- [ ] archive old `wpsvg` "pro" repo

### Designs

n/a

### Describe alternatives you've considered

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Sidsector9**
Closes #90 

## Note

Before merging, check if all tasks in the issue are completed.

### Description of the Change
This PR drops the support level from Active to Stable. There's a similar [support forum post on WP.org](https://wordpress.org/support/topic/read-this-before-you-post-56/) that attempts to avoid support issues there and instead push folks to GitHub as well as note that bugs and security issues get priority, PRs for enhancements will be considered, but otherwise we intend to test against major WordPress versions only.

### How to test the Change
n/a

### Changelog Entry

> Changed - Support Level from Active to Stable

### Credits

Props @jeffpaul, @Sidsector9  

### Checklist:

- [x] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by iamdharmesh — DISMISSED** [review]
Thanks for adding this @Sidsector9. LGTM.

**Note: Please do not merge before tasks in the issue are completed.**

**Comment by jeffpaul** [comment]
Added support forum sticky post: https://wordpress.org/support/topic/read-this-before-you-post-70/

**Comment by jeffpaul** [comment]
@iamdharmesh this is back to you for review/merging

**Review by iamdharmesh — APPROVED** [review]
:shipit:

**Pull request merged**
