### PR TITLE
Stop distributing development files

### LINKED ISSUE #97: NPM archive related scripts include node_modules and vendor files in zip.
### Describe the bug

When building an archive using the NPM `archive` and `postarchive` scripts, the `node_modules` and `vendor` folders are included in the zip file.

In local testing, this created a 69.6 MB zip file.

### Steps to Reproduce

1. Check out develop branch.
2. Run `npm i; composer i; npm run build;`
3. Run `npm run archive` -- observe the node and vendor folders are included in the zip
4. Run `npm run postarchive`
5. Run `cd safe-svg; ls`
6. Observe the unzipped files also include the node_modules and vendor folders

### Screenshots, screen recording, code snippet

_No response_

### Environment information

- Device: macbook pro 2020
- OS: macOS 12.6.2

### WordPress information

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by szepeviktor**
Resolves #97

Here is how to test.
```bash
git archive HEAD | tar --list
```

### CODE REVIEW

**Comment by szepeviktor** [comment]
💡 There is a safeguard for this problem.
https://github.com/szepeviktor/byte-level-care/blob/61ca4439630a47d4e6946173a369270a4729bfb2/.github/workflows/reusable-integrity.yml#L160-L171

**Comment by peterwilsoncc** [comment]
@szepeviktor Thanks for the pull request and linking to your workflow file.

The generated zip file contains a few files that are listed in the `.gitignore` file. By default `git archive` ignores these files, do you know if there is a method that will allow safe-svg to include these files when generating the zip file via `git archive`?

The affected files are:
* built assets in the `/dist` directory
* production assets included in the `/vendor` directory

I've hit a few road-blocks trying to figure it out, so would value any input.

**Comment by szepeviktor** [comment]
> do you know if there is a method that will allow safe-svg to include these files

There is an option for that: https://git-scm.com/docs/git-archive#Documentation/git-archive.txt---add-fileltfilegt

BTW .gitignore is unrelated to .gitattributes

**Comment by jeffpaul** [comment]
Isn't this covered by the [`.distignore` file](https://github.com/10up/safe-svg/blob/develop/.distignore)?

**Comment by szepeviktor** [comment]
Maybe.
Composer uses GitHub ZIP, those are not affected by distignore.

**Comment by jeffpaul** [comment]
Closing in favor of alternate handling of #97 in #220.

**Pull request closed without merging**
